spring:
  config:
    activate:
      on-profile: local
  sql:
    init:
      mode: always
      data-locations:
        - classpath:product-data.sql
        - classpath:review-data.sql
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:eccomerce
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true